packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.13
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  ai: ^5.0.49
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  hono: ^4.8.2
  mongoose: ^8.14.0
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: 4.1.12
